### ISSUE TITLE
Extend magenta navigation bar to the right

### ISSUE THREAD

**Issue by flxai** [freifunkks/freifunkks.github.com#3]
I'd welcome it, if the navigation bar could be extended to the right, like depicted.

![ffks_magenta_snippet](https://cloud.githubusercontent.com/assets/10831300/6198758/ea62e90e-b416-11e4-9d70-63306f5f6961.gif)

**Comment by jplatte** [comment]
I'll try to do this and have a look at it locally. I generally like the idea, but I have a feeling it might look bad on wide (1600px of more)  screens. If it looks good though, I'll commit it.

**Comment by jplatte** [comment]
I'm still unsure. Do you think this looks good?
![screenshot](https://cloud.githubusercontent.com/assets/951129/6200291/4071372e-b471-11e4-9eaa-8633ca97da2e.png)

**Comment by flxai** [comment]
Your guts didn't fool you. Looked better before.
Thanks for trying it out.
